steps:
  # Etapa 1: Instala dependências do Frontend
  - name: 'node:20'
    entrypoint: 'npm'
    dir: 'frontend'
    args: ['install']

  # Etapa 2: Build do Frontend injetando variáveis de ambiente (Produção)
  - name: 'node:20'
    entrypoint: 'npm'
    dir: 'frontend'
    args: ['run', 'build']
    env:
      - 'VITE_API_URL=$_API_URL'
      - 'VITE_FIREBASE_API_KEY=$_FIREBASE_API_KEY'
      - 'VITE_FIREBASE_AUTH_DOMAIN=$_FIREBASE_AUTH_DOMAIN'
      - 'VITE_FIREBASE_PROJECT_ID=$_FIREBASE_PROJECT_ID'
      - 'VITE_FIREBASE_STORAGE_BUCKET=$_FIREBASE_STORAGE_BUCKET'
      - 'VITE_FIREBASE_MESSAGING_SENDER_ID=$_FIREBASE_MESSAGING_SENDER_ID'
      - 'VITE_FIREBASE_APP_ID=$_FIREBASE_APP_ID'

  # Etapa 3: Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/monitoria-cx:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/monitoria-cx:latest',
      '.'
    ]

  # Etapa 4: Push das imagens construídas para o Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/monitoria-cx:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/monitoria-cx:latest']

  # Etapa 5: Deploy do container atualizado no Cloud Run (Teste)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'beta'
      - 'run'
      - 'deploy'
      - 'monitoria-test-env'
      - '--image'
      - 'gcr.io/$PROJECT_ID/monitoria-cx:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--execution-environment=gen2'
      - '--add-volume=name=db-vol,type=cloud-storage,bucket=consultoria-bess-mme136-db-bucket'
      - '--add-volume-mount=volume=db-vol,mount-path=/mnt/db'
      - '--allow-unauthenticated'
      - '--cpu=4'
      - '--memory=8Gi'
      - '--quiet'

images:
  - 'gcr.io/$PROJECT_ID/monitoria-cx:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/monitoria-cx:latest'
