steps:
  # Etapa 1: Build da imagem Docker do WORKER
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'Dockerfile.worker',
      '-t', 'gcr.io/$PROJECT_ID/monitoria-whisper-worker:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/monitoria-whisper-worker:latest',
      '.'
    ]

  # Etapa 2: Push das imagens
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/monitoria-whisper-worker:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/monitoria-whisper-worker:latest']

images:
  - 'gcr.io/$PROJECT_ID/monitoria-whisper-worker:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/monitoria-whisper-worker:latest'