steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.loadtest', '-t', 'gcr.io/$PROJECT_ID/monitoria-loadtest:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/monitoria-loadtest:$COMMIT_SHA']
images:
  - 'gcr.io/$PROJECT_ID/monitoria-loadtest:$COMMIT_SHA'